services:
  postgres:
    image: postgres:16-alpine
    container_name: lans_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: lans_style
      POSTGRES_USER: lans
      POSTGRES_PASSWORD: lans_secret
    volumes:
      - pgdata:/var/lib/postgresql/data
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: lans_server
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://lans:lans_secret@postgres:5432/lans_style
      PORT: 5000
      JWT_SECRET: lans-jwt-secret-prod
      ADMIN_LOGIN: lans-admin
      ADMIN_PASSWORD: n3I2D~uVU
      NODE_ENV: production
      TELEGRAM_BOT_TOKEN: 8625164504:AAF1PGjomSfow53IBJ2Lyax0bxDiPLSvghA
      TELEGRAM_ADMIN_IDS: "7506120714"
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: "465"
      SMTP_USER: opt.lansstyle@gmail.com
      SMTP_PASS: cfxfxopbxgupkuex
      EMAIL_FROM: "Lans Style <opt.lansstyle@gmail.com>"
    volumes:
      - ./server/uploads:/app/uploads
    depends_on:
      - postgres
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: lans_client
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - server
volumes:
  pgdata:
