ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "isArchived"     BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "costumeItem3Id" INTEGER;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "costumeItem4Id" INTEGER;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "costumeItem5Id" INTEGER;

ALTER TABLE "Product" ADD CONSTRAINT "Product_costumeItem3Id_fkey"
  FOREIGN KEY ("costumeItem3Id") REFERENCES "Product"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Product" ADD CONSTRAINT "Product_costumeItem4Id_fkey"
  FOREIGN KEY ("costumeItem4Id") REFERENCES "Product"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Product" ADD CONSTRAINT "Product_costumeItem5Id_fkey"
  FOREIGN KEY ("costumeItem5Id") REFERENCES "Product"("id") ON DELETE SET NULL ON UPDATE CASCADE;
